# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mod_ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mod_ekrani(object):
    def setupUi(self, mod_ekrani):
        mod_ekrani.setObjectName("mod_ekrani")
        mod_ekrani.resize(462, 295)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/azakSihaIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mod_ekrani.setWindowIcon(icon)
        mod_ekrani.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.centralwidget = QtWidgets.QWidget(mod_ekrani)
        self.centralwidget.setObjectName("centralwidget")
        self.mod_durumu = QtWidgets.QLabel(self.centralwidget)
        self.mod_durumu.setGeometry(QtCore.QRect(100, 20, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mod_durumu.setFont(font)
        self.mod_durumu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(193, 225, 229);")
        self.mod_durumu.setObjectName("mod_durumu")
        self.auto_buton = QtWidgets.QPushButton(self.centralwidget)
        self.auto_buton.setGeometry(QtCore.QRect(100, 100, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auto_buton.setFont(font)
        self.auto_buton.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"color: rgb(0, 0, 0);")
        self.auto_buton.setObjectName("auto_buton")
        self.loiter_buton = QtWidgets.QPushButton(self.centralwidget)
        self.loiter_buton.setGeometry(QtCore.QRect(240, 170, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loiter_buton.setFont(font)
        self.loiter_buton.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"color: rgb(0, 0, 0);")
        self.loiter_buton.setObjectName("loiter_buton")
        self.rtl_buton = QtWidgets.QPushButton(self.centralwidget)
        self.rtl_buton.setGeometry(QtCore.QRect(240, 100, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rtl_buton.setFont(font)
        self.rtl_buton.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"color: rgb(0, 0, 0);")
        self.rtl_buton.setObjectName("rtl_buton")
        self.manual_buton = QtWidgets.QPushButton(self.centralwidget)
        self.manual_buton.setGeometry(QtCore.QRect(100, 170, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.manual_buton.setFont(font)
        self.manual_buton.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"color: rgb(0, 0, 0);")
        self.manual_buton.setObjectName("manual_buton")
        mod_ekrani.setCentralWidget(self.centralwidget)

        self.retranslateUi(mod_ekrani)
        QtCore.QMetaObject.connectSlotsByName(mod_ekrani)

    def retranslateUi(self, mod_ekrani):
        _translate = QtCore.QCoreApplication.translate
        mod_ekrani.setWindowTitle(_translate("mod_ekrani", "Mod Ekranı"))
        self.mod_durumu.setText(_translate("mod_ekrani", " Mod : "))
        self.auto_buton.setText(_translate("mod_ekrani", "Auto"))
        self.loiter_buton.setText(_translate("mod_ekrani", "Loiter"))
        self.rtl_buton.setText(_translate("mod_ekrani", "RTL"))
        self.manual_buton.setText(_translate("mod_ekrani", "Manual"))
import icons_rc
