# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Uydu_Hud_Ekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import icons_rc
from PyQt5 import QtCore, QtGui, QtWidgets
from hud_widget import HudWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 691)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/azakSihaIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uydu_goruntusu_widget = QtWidgets.QWidget(self.centralwidget)
        self.uydu_goruntusu_widget.setGeometry(QtCore.QRect(0, 0, 651, 691))
        self.uydu_goruntusu_widget.setObjectName("uydu_goruntusu_widget")
        self.hud_container = HudWidget(self.centralwidget)
        self.hud_container.setGeometry(QtCore.QRect(660, 0, 481, 691))
        self.hud_container.setObjectName("hud_container")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Uydu Hud Ekranı"))

